"""Generate ``games/rag_tag/fighters.py`` from ``games/rag_tag/data/*.json``.

    python -m games.rag_tag.tools.import_bga [--check]

``fighters.py`` is generated and committed, so the engine imports plain Python and
the transform stays reviewable. This script is the source of truth for the
transform: a corrected dump is a re-run, never a re-transcription.

``--check`` regenerates in memory and exits non-zero if the committed file differs.
That is what ``tests/test_fighters.py`` calls, so an edit to the data — or to this
script — that was never re-run fails the suite instead of drifting quietly.

The data itself is validated on the way through (see ``effects.validate_ops``),
so a card naming an op the engine has never heard of fails HERE, with its path,
rather than resolving to nothing at the table.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import pprint
import sys

if __package__ in (None, ""):  # allow `python games/rag_tag/tools/import_bga.py`
    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[3]))

from games.rag_tag import effects

PKG = pathlib.Path(__file__).resolve().parent.parent
DATA = PKG / "data"
OUT = PKG / "fighters.py"

HEADER = '''"""The 12 base-box fighters: boards, health tracks and decks.

GENERATED by ``tools/import_bga.py`` from ``data/boards.json`` + ``data/cards.json``
— do not edit by hand. ``tests/test_fighters.py`` re-runs the generator and fails
if this file is stale, so an edit here is not merely lost, it is caught.

    FIGHTERS      fighter id -> board (base Power, health track, special track, tokens)
    CARDS         card id -> card (name, copies, ops, instant bonus)
    DECKS         fighter id -> the 10 card ids in that fighter's deck, copies expanded
    STARTING_CARD fighter id -> the card set aside at setup as half the Fight Deck
    MILADY_SCHEMES the 9 distinct Intrigue effects across her 11 tokens
    ROSTER        every fighter id, in board order
"""
'''


def _load(name: str) -> dict:
    return json.loads((DATA / name).read_text(encoding="utf-8"))


def _strip_comments(obj):
    """Drop the ``_comment`` keys the JSON carries for human readers."""
    if isinstance(obj, dict):
        return {k: _strip_comments(v) for k, v in obj.items() if not k.startswith("_")}
    if isinstance(obj, list):
        return [_strip_comments(v) for v in obj]
    return obj


def _validate_track(track, path: str) -> None:
    """A health track runs bottom-to-top and must be able to end a fighter."""
    if not track:
        raise effects.OpError(f"{path}: empty health track")
    kinds = [space.get("kind") for space in track]
    if "ko" not in kinds and "spirit" not in kinds:
        raise effects.OpError(
            f"{path}: no KO and no Spirit space — this fighter cannot be finished")
    starts = [i for i, s in enumerate(track) if s.get("start")]
    if len(starts) != 1:
        raise effects.OpError(f"{path}: expected exactly one start space, got {len(starts)}")
    if track[starts[0]].get("kind") != "hp":
        raise effects.OpError(f"{path}: the start space is not an HP space")
    hp = [s["hp"] for s in track if s.get("kind") == "hp"]
    if hp != sorted(hp):
        raise effects.OpError(f"{path}: HP numbers are not ascending bottom-to-top")
    for i, space in enumerate(track):
        effects.validate_icons(space.get("icons", []), f"{path}[{i}].icons")


def build() -> dict:
    boards = _strip_comments(_load("boards.json"))
    cards_doc = _strip_comments(_load("cards.json"))

    fighters = boards["fighters"]
    roster = tuple(fighters)

    # --- boards -----------------------------------------------------------
    for fid, board in fighters.items():
        if board.get("hp_track"):
            _validate_track(board["hp_track"], f"{fid}.hp_track")
        for ch in board.get("characters", ()):
            _validate_track(ch["hp_track"], f"{fid}.{ch['id']}.hp_track")
        if board.get("back"):
            back = board["back"]["hp_track"]
            # The Bear's marker is placed by the transformation, not at setup,
            # so his track carries no start space and _validate_track's rule
            # would be wrong for him. Check what still applies.
            if not any(s.get("kind") == "ko" for s in back):
                raise effects.OpError(f"{fid}.back.hp_track: no KO space")
        effects.validate_ops(board.get("setup_icons", []), f"{fid}.setup_icons")
        track = board.get("special_track")
        if track:
            for i, space in enumerate(track.get("spaces", ())):
                effects.validate_ops(space.get("icons", []),
                                     f"{fid}.special_track[{i}].icons")

    # --- cards ------------------------------------------------------------
    cards: dict[int, dict] = {}
    decks: dict[str, list[int]] = {fid: [] for fid in fighters}
    starting: dict[str, int] = {}

    for card in cards_doc["cards"]:
        cid, fid = card["id"], card["fighter"]
        if fid not in fighters:
            raise effects.OpError(f"card {cid}: unknown fighter {fid!r}")
        if cid in cards:
            raise effects.OpError(f"card {cid}: duplicate id")
        where = f"card {cid} ({card['name']})"
        effects.validate_ops(card["ops"], f"{where}.ops")
        if "ops_back" in card:
            effects.validate_ops(card["ops_back"], f"{where}.ops_back")
        if "instant_bonus" in card:
            effects.validate_ops(card["instant_bonus"], f"{where}.instant_bonus")
        cards[cid] = card
        decks[fid].extend([cid] * card["copies"])
        if card.get("starting"):
            if fid in starting:
                raise effects.OpError(f"{fid}: two starting cards")
            starting[fid] = cid

    for fid in fighters:
        if len(decks[fid]) != 10:
            raise effects.OpError(f"{fid}: deck is {len(decks[fid])} cards, expected 10")
        if fid not in starting:
            raise effects.OpError(f"{fid}: no starting card")

    schemes = cards_doc["milady_schemes"]
    for i, eff in enumerate(schemes["effects"]):
        effects.validate_ops(eff["ops"], f"milady_scheme[{eff['id']}]")

    return {
        "FIGHTERS": fighters,
        "CARDS": cards,
        "DECKS": {fid: tuple(sorted(v)) for fid, v in decks.items()},
        "STARTING_CARD": starting,
        "MILADY_SCHEMES": schemes,
        "ROSTER": roster,
    }


def render(built: dict) -> str:
    out = [HEADER]
    for name in ("ROSTER", "FIGHTERS", "CARDS", "DECKS", "STARTING_CARD", "MILADY_SCHEMES"):
        out.append(f"{name} = " + pprint.pformat(built[name], width=96, sort_dicts=False))
        out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed fighters.py is stale")
    args = ap.parse_args()

    text = render(build())
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is STALE — re-run: python -m games.rag_tag.tools.import_bga")
            return 1
        print(f"{OUT} is up to date")
        return 0

    OUT.write_text(text, encoding="utf-8")
    built = build()
    print(f"wrote {OUT}: {len(built['ROSTER'])} fighters, {len(built['CARDS'])} cards, "
          f"{sum(len(d) for d in built['DECKS'].values())} copies")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
