"""Generate duel-core/src/cards.rs from games/spender_duel/cards.py.

SINGLE SOURCE OF TRUTH: the Python deck is authoritative; this dumps it verbatim as
Rust consts so the port can never drift from it. Re-run after ANY card-data change
(and re-run the parity suite, which would catch a drift anyway).

    python duel-core/tools/gen_cards.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, REPO)

from games.spender_duel import cards as C  # noqa: E402

# Canonical index: deck order, level 1 then 2 then 3. Rust refers to cards by this
# index; `bridge.rs`/the parity harness map it back to the Python string id.
IDS = C.deck_ids(1) + C.deck_ids(2) + C.deck_ids(3)
assert len(IDS) == len(C.CARDS) == 67, (len(IDS), len(C.CARDS))
assert len(set(IDS)) == len(IDS)

COST_ORDER = C.COLORS + ["pearl"]                  # white blue green red black pearl
BONUS_CODE = {None: -1, "wild": 5, **{c: i for i, c in enumerate(C.COLORS)}}
ABIL = {None: 0, "again": 1, "take_same": 2, "privilege": 3, "steal": 4}
TOKEN_CODE = {t: i for i, t in enumerate(C.TOKENS)}  # ...pearl=5, gold=6


def rows(xs):
    return ",\n    ".join(xs)


cards = C.CARDS
out = [
    "// AUTO-GENERATED by duel-core/tools/gen_cards.py — DO NOT EDIT.",
    "// Source: games/spender_duel/cards.py (the real Splendor Duel deck).",
    "// Color order: white=0 blue=1 green=2 red=3 black=4 | pearl=5 gold=6.",
    "// Card index = deck order: level 1 (0..29), level 2 (30..53), level 3 (54..66).",
    "",
    f"pub const N_CARDS: usize = {len(IDS)};",
    f"pub const N_ROYALS: usize = {len(C.ROYALS)};",
    "pub const N_COLORS: usize = 5;",
    "pub const PEARL: usize = 5;",
    "pub const GOLD: usize = 6;",
    "pub const N_TOKENS: usize = 7;",
    "",
    "/// Bonus: 0..4 = colour, 5 = wild, -1 = none.",
    "pub const BONUS_WILD: i8 = 5;",
    "pub const BONUS_NONE: i8 = -1;",
    "/// Ability: 0 none, 1 again, 2 take_same, 3 privilege, 4 steal.",
    "pub const AB_NONE: u8 = 0;",
    "pub const AB_AGAIN: u8 = 1;",
    "pub const AB_TAKE_SAME: u8 = 2;",
    "pub const AB_PRIVILEGE: u8 = 3;",
    "pub const AB_STEAL: u8 = 4;",
    "",
    "/// Post-bonus cost is computed against colours 0..4; index 5 is pearls (no bonus).",
    f"pub const COST: [[i32; 6]; {len(IDS)}] = [\n    "
    + rows("[" + ", ".join(str(cards[i]["cost"].get(c, 0)) for c in COST_ORDER) + "]" for i in IDS)
    + ",\n];",
    "",
    f"pub const LEVEL_OF: [u8; {len(IDS)}] = [{', '.join(str(cards[i]['level']) for i in IDS)}];",
    f"pub const PTS: [i32; {len(IDS)}] = [{', '.join(str(cards[i]['points']) for i in IDS)}];",
    f"pub const CROWNS: [i32; {len(IDS)}] = [{', '.join(str(cards[i]['crowns']) for i in IDS)}];",
    f"pub const BONUS: [i8; {len(IDS)}] = [{', '.join(str(BONUS_CODE[cards[i]['bonus']]) for i in IDS)}];",
    f"pub const BONUS_COUNT: [i32; {len(IDS)}] = [{', '.join(str(cards[i]['bonus_count']) for i in IDS)}];",
    f"pub const ABILITY: [u8; {len(IDS)}] = [{', '.join(str(ABIL[cards[i]['ability']]) for i in IDS)}];",
    "",
    f"pub const DECK_SIZES: [usize; 3] = [{C.DECK_SIZES[1]}, {C.DECK_SIZES[2]}, {C.DECK_SIZES[3]}];",
    f"pub const PYRAMID_SIZES: [usize; 3] = [{C.PYRAMID_SIZES[1]}, {C.PYRAMID_SIZES[2]}, {C.PYRAMID_SIZES[3]}];",
    "/// First card index of each level, so level L's deck is IDS[OFF[L]..OFF[L]+DECK_SIZES[L]].",
    f"pub const LEVEL_OFF: [usize; 3] = [0, {C.DECK_SIZES[1]}, {C.DECK_SIZES[1] + C.DECK_SIZES[2]}];",
    "",
    f"pub const ROYAL_PTS: [i32; {len(C.ROYALS)}] = "
    f"[{', '.join(str(C.ROYALS[r]['points']) for r in sorted(C.ROYALS))}];",
    f"pub const ROYAL_ABILITY: [u8; {len(C.ROYALS)}] = "
    f"[{', '.join(str(ABIL[C.ROYALS[r]['ability']]) for r in sorted(C.ROYALS))}];",
    "",
    "/// The bag's exact 25-token multiset (token codes).",
    f"pub const TOKEN_BAG: [u8; {len(C.TOKEN_BAG)}] = "
    f"[{', '.join(str(TOKEN_CODE[t]) for t in C.TOKEN_BAG)}];",
    "/// Printed centre-out spiral: replenish fills empty cells in this order.",
    f"pub const SPIRAL_ORDER: [usize; 25] = [{', '.join(str(i) for i in C.SPIRAL_ORDER)}];",
    "",
    "pub const MAX_TOKENS: i32 = 10;",
    "pub const MAX_RESERVED: usize = 3;",
    "pub const WIN_POINTS: i32 = 20;",
    "pub const WIN_CROWNS: i32 = 10;",
    "pub const WIN_COLOR_POINTS: i32 = 10;",
    "",
]
dst = os.path.join(HERE, "..", "src", "cards.rs")
with open(dst, "w") as f:
    f.write("\n".join(out))
print(f"wrote {os.path.normpath(dst)}: {len(IDS)} cards, {len(C.ROYALS)} royals")
