// AUTO-GENERATED by duel-core/tools/gen_cards.py — DO NOT EDIT.
// Source: games/spender_duel/cards.py (the real Splendor Duel deck).
// Color order: white=0 blue=1 green=2 red=3 black=4 | pearl=5 gold=6.
// Card index = deck order: level 1 (0..29), level 2 (30..53), level 3 (54..66).

pub const N_CARDS: usize = 67;
pub const N_ROYALS: usize = 4;
pub const N_COLORS: usize = 5;
pub const PEARL: usize = 5;
pub const GOLD: usize = 6;
pub const N_TOKENS: usize = 7;

/// Bonus: 0..4 = colour, 5 = wild, -1 = none.
pub const BONUS_WILD: i8 = 5;
pub const BONUS_NONE: i8 = -1;
/// Ability: 0 none, 1 again, 2 take_same, 3 privilege, 4 steal.
pub const AB_NONE: u8 = 0;
pub const AB_AGAIN: u8 = 1;
pub const AB_TAKE_SAME: u8 = 2;
pub const AB_PRIVILEGE: u8 = 3;
pub const AB_STEAL: u8 = 4;

/// Post-bonus cost is computed against colours 0..4; index 5 is pearls (no bonus).
pub const COST: [[i32; 6]; 67] = [
    [0, 1, 1, 1, 1, 0],
    [0, 3, 0, 0, 0, 0],
    [0, 2, 2, 0, 0, 1],
    [0, 0, 0, 2, 2, 0],
    [0, 0, 2, 3, 0, 0],
    [1, 0, 1, 1, 1, 0],
    [0, 0, 3, 0, 0, 0],
    [0, 0, 2, 2, 0, 1],
    [2, 0, 0, 0, 2, 0],
    [0, 0, 0, 2, 3, 0],
    [1, 1, 0, 1, 1, 0],
    [0, 0, 0, 3, 0, 0],
    [0, 0, 0, 2, 2, 1],
    [2, 2, 0, 0, 0, 0],
    [3, 0, 0, 0, 2, 0],
    [1, 1, 1, 0, 1, 0],
    [0, 0, 0, 0, 3, 0],
    [2, 0, 0, 0, 2, 1],
    [0, 2, 2, 0, 0, 0],
    [2, 3, 0, 0, 0, 0],
    [1, 1, 1, 1, 0, 0],
    [3, 0, 0, 0, 0, 0],
    [2, 2, 0, 0, 0, 1],
    [0, 0, 2, 2, 0, 0],
    [0, 2, 3, 0, 0, 0],
    [0, 0, 0, 0, 4, 1],
    [4, 0, 0, 0, 0, 1],
    [0, 2, 0, 2, 1, 1],
    [2, 0, 2, 0, 1, 1],
    [0, 0, 0, 4, 0, 1],
    [0, 0, 2, 2, 2, 1],
    [0, 4, 0, 3, 0, 0],
    [4, 0, 0, 0, 2, 1],
    [0, 5, 2, 0, 0, 0],
    [2, 0, 0, 2, 2, 1],
    [0, 0, 4, 0, 3, 0],
    [2, 4, 0, 0, 0, 1],
    [0, 0, 5, 2, 0, 0],
    [2, 2, 0, 0, 2, 1],
    [3, 0, 0, 4, 0, 0],
    [0, 2, 4, 0, 0, 1],
    [0, 0, 0, 5, 2, 0],
    [2, 2, 2, 0, 0, 1],
    [0, 3, 0, 0, 4, 0],
    [0, 0, 2, 4, 0, 1],
    [2, 0, 0, 0, 5, 0],
    [0, 2, 2, 2, 0, 1],
    [4, 0, 3, 0, 0, 0],
    [0, 0, 0, 2, 4, 1],
    [5, 2, 0, 0, 0, 0],
    [0, 0, 6, 0, 0, 1],
    [0, 0, 6, 0, 0, 1],
    [0, 6, 0, 0, 0, 1],
    [0, 6, 0, 0, 0, 1],
    [0, 3, 0, 5, 3, 1],
    [6, 2, 0, 0, 2, 0],
    [3, 0, 3, 0, 5, 1],
    [2, 6, 2, 0, 0, 0],
    [5, 3, 0, 3, 0, 1],
    [0, 2, 6, 2, 0, 0],
    [0, 5, 3, 0, 3, 1],
    [0, 0, 2, 6, 2, 0],
    [3, 0, 5, 3, 0, 1],
    [2, 0, 0, 2, 6, 0],
    [0, 0, 0, 8, 0, 0],
    [0, 0, 0, 0, 8, 0],
    [8, 0, 0, 0, 0, 0],
];

pub const LEVEL_OF: [u8; 67] = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3];
pub const PTS: [i32; 67] = [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 3, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 0, 0, 5, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 0, 6];
pub const CROWNS: [i32; 67] = [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 3, 0];
pub const BONUS: [i8; 67] = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, -1, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, -1, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, -1];
pub const BONUS_COUNT: [i32; 67] = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
pub const ABILITY: [u8; 67] = [0, 0, 1, 2, 0, 0, 0, 1, 2, 0, 0, 0, 1, 2, 0, 0, 0, 1, 2, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 4, 3, 0, 0, 4, 3, 0, 0, 4, 3, 0, 0, 4, 3, 0, 0, 4, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0];

pub const DECK_SIZES: [usize; 3] = [30, 24, 13];
pub const PYRAMID_SIZES: [usize; 3] = [5, 4, 3];
/// First card index of each level, so level L's deck is IDS[OFF[L]..OFF[L]+DECK_SIZES[L]].
pub const LEVEL_OFF: [usize; 3] = [0, 30, 54];

pub const ROYAL_PTS: [i32; 4] = [3, 2, 2, 2];
pub const ROYAL_ABILITY: [u8; 4] = [0, 1, 4, 3];

/// The bag's exact 25-token multiset (token codes).
pub const TOKEN_BAG: [u8; 25] = [0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6, 6];
/// Printed centre-out spiral: replenish fills empty cells in this order.
pub const SPIRAL_ORDER: [usize; 25] = [12, 7, 6, 11, 16, 17, 18, 13, 8, 3, 2, 1, 0, 5, 10, 15, 20, 21, 22, 23, 24, 19, 14, 9, 4];

pub const MAX_TOKENS: i32 = 10;
pub const MAX_RESERVED: usize = 3;
pub const WIN_POINTS: i32 = 20;
pub const WIN_CROWNS: i32 = 10;
pub const WIN_COLOR_POINTS: i32 = 10;
