#!/bin/bash
# Extended-training pass on w03 (the attention-distill lesson: +15pp from extra
# warm epochs at halved lr; val metrics are blind to it — always re-GATE), then
# the consolidation loop in the winner's OWN basin (champion-warm is dead:
# 0.4958 -> 0.4250). Seeds loop_coc_aux.sh with whichever of w03 / w03_ext
# gates higher vs the champion.
set -o pipefail
RUN=/c/Users/Forrest/coc_run_aux
RUNW=$(cygpath -m "$RUN")
CR=/c/Users/Forrest/forrestm_projects/coc-core/target/release
TOOLS=/c/Users/Forrest/forrestm_projects/coc-core/tools
CHAMP=C:/Users/Forrest/coc_run_r2/pv_ship_r2.json
LOG=$RUN/overnight_log.txt
W03_CHAMP=0.4625   # w03's measured champion gate (n=240) — the bar for ext
CHILDREN=""
killtree() { taskkill //PID "$1" //T //F >/dev/null 2>&1 || true; }
reap_gpu_servers() {
    powershell -NoProfile -Command \
        "Get-CimInstance Win32_Process -Filter \"Name='python.exe'\" | Where-Object { \$_.CommandLine -match 'gpu_server' } | ForEach-Object { Stop-Process -Id \$_.ProcessId -Force -ErrorAction SilentlyContinue }" \
        >/dev/null 2>&1 || true
}
cleanup() { for p in $CHILDREN; do killtree "$p"; done; reap_gpu_servers; }
trap cleanup EXIT
start_server() { # model, port, logname -> sets SRV_PID
    COC_GPU_PAD=48 python "$TOOLS/gpu_server.py" "$1" --port "$2" >"$RUN/$3" 2>&1 &
    SRV_PID=$!
    CHILDREN="$CHILDREN $SRV_PID"
    for _ in $(seq 1 30); do grep -q "ready" "$RUN/$3" 2>/dev/null && break; sleep 2; done
    grep -q "ready" "$RUN/$3" || { echo "FATAL: gate server $3 never came up" | tee -a "$LOG"; exit 1; }
}
gate() { # A_spec, B_spec, seed, label -> stdout = win rate
    local g
    g=$("$CR/gate_coc.exe" "$1" "$2" 120 200 200 "$3" 4 24 2>>"$RUN/gates_err_ext.log" | tail -1)
    echo "GATE $4: $g" >>"$LOG"
    echo "$g" | sed -E 's/.*: ([0-9.]+) \+-.*/\1/'
}

echo "=== extended training on w03 (warm, lr 5e-4, +4 epochs) ===" | tee -a "$LOG"
CUDA_LAUNCH_BLOCKING=1 python "$TOOLS/train_pv.py" --data "$RUNW/aux_boot.t*.csv" \
    --out "$RUNW/pv_aux_w03_ext.json" --warm "$RUNW/pv_aux_w03.json" \
    --epochs 4 --lr 5e-4 --aux-dim 14 --aux-weight 0.3 2>&1 | tee -a "$LOG" || {
    echo "ext train CRASHED — retrying once" | tee -a "$LOG"
    CUDA_LAUNCH_BLOCKING=1 python "$TOOLS/train_pv.py" --data "$RUNW/aux_boot.t*.csv" \
        --out "$RUNW/pv_aux_w03_ext.json" --warm "$RUNW/pv_aux_w03.json" \
        --epochs 4 --lr 5e-4 --aux-dim 14 --aux-weight 0.3 2>&1 | tee -a "$LOG"
}
"$CR/net_export_check.exe" "$RUNW/pv_aux_w03_ext.json" 2>&1 | tee -a "$LOG"

echo "=== ext gates ===" | tee -a "$LOG"
reap_gpu_servers
start_server "$RUNW/pv_aux_w03_ext.json" 9942 gpu_ext.log; p1=$SRV_PID
start_server "$RUNW/pv_aux_w03.json" 9943 gpu_ext_w03.log; p2=$SRV_PID
ext_champ=$(COC_GPU_ADDR_A=127.0.0.1:9942 gate "$RUNW/pv_aux_w03_ext.json:netvalgpu" "$CHAMP:netval" 21011 "w03ext-vs-champ")
ext_w03=$(COC_GPU_ADDR_A=127.0.0.1:9942 COC_GPU_ADDR_B=127.0.0.1:9943 \
    gate "$RUNW/pv_aux_w03_ext.json:netvalgpu" "$RUNW/pv_aux_w03.json:netvalgpu" 21012 "w03ext-vs-w03-DIRECT")
killtree "$p1"; killtree "$p2"
reap_gpu_servers
echo "SUMMARY(ext) ext_champ=$ext_champ ext_vs_w03=$ext_w03 (w03 bar $W03_CHAMP)" | tee -a "$LOG"

seed_net="$RUNW/pv_aux_w03.json"
if awk "BEGIN{exit !($ext_champ >= $W03_CHAMP)}" 2>/dev/null; then
    seed_net="$RUNW/pv_aux_w03_ext.json"
fi
echo "LOOP SEED: $seed_net" | tee -a "$LOG"

# reset the loop state left by the champion-warm run — its sp_*/lg_* harvests
# were generated by the CHAMPION and must NOT feed a w03-basin loop; keep the
# anchor corpora (aux_boot, lg_aux)
rm -f "$RUN"/progress_aux "$RUN"/aux_best.json "$RUN"/aux_best.json.check \
      "$RUN"/aux_cand_*.json "$RUN"/aux_cand_*.json.check \
      "$RUN"/sp_[0-9]*.t*.csv "$RUN"/sp_[0-9]*.HARVESTED \
      "$RUN"/lg_[0-9]*.t*.csv "$RUN"/lg_[0-9]*.HARVESTED 2>/dev/null || true
rm -rf "$RUN/loop_aux.lock" 2>/dev/null || true
echo "=== starting consolidation loop in own basin ===" | tee -a "$LOG"
SEED_NET="$seed_net" exec bash "$TOOLS/loop_coc_aux.sh"
