"""engine_leak_probe.py — does ACQUIRING an engine card RAISE the leaf value V?

HYPOTHESIS (user): v_state's `progress` term feeds `take_value` (a MARGINAL-ACQUISITION
metric) into a slot meant to measure POSITIONAL STRENGTH, and `engine_stock` credits held
bonuses ONLY against the undealt DECK (deck_color_demand), never the board. So when you buy
an engine card off the board:
  - `progress` LOSES that card's `take_value` (incl. its board-discount `engine_value`),
  - `engine_stock` recaptures only the small DECK slice of the new bonus,
  - the remaining board cards get cheaper (progress point-part up) but their engine_value
    drops (flatter convexity) -- roughly a wash.
=> building engine reads as value-neutral/negative in the leaf -> S under-builds (the
documented turn 9-14 engine-race loss).

This probe measures it two ways on realistic self-play positions, bucketed by game stage
(the mover's purchased-card count):

  FREE ACQUIRE: clone, remove the best engine card from the board and grant its +1 bonus
                with NO payment and NO turn pass. Isolates the pure EVAL leak: if even a
                free bonus doesn't raise V, the positional value simply isn't represented.
  REAL BUY    : clone, actually buy that card if AFFORDABLE (pays tokens, ends the turn).
                dV = V(after) - V(before) from the MOVER's perspective.

Per-component standing deltas (weighted W_x * Δcomponent) are reported for the FREE-acquire
case, so you can see WHICH term moves: engine_stock (the deck recapture) vs progress (the
drain) vs points.

For contrast it also reports the REAL-BUY dV of the best affordable POINT card (PTS>0) --
the eval is expected to reward those, so a large point>engine gap is the smoking gun.

"Engine card" = board card with PTS == 0 and engine_value > 0; "best" = max engine_value.
Positions are generated by H3 greedy self-play (fast; the leaf is a static function, so the
generator only shapes the position distribution, not the measurement).

Run from the PRIMARY (main) worktree so it measures the DEPLOYED leaf:
    python -m games.spender.ai.offline.engine_leak_probe --games 200 --seed 1
"""
from __future__ import annotations

import argparse
import random

from ..serving import engine as E
from ..serving import heuristic3 as H3
from ..serving import v_state as VS
from ..serving import valuation3 as V

COMPS = ("points", "engine", "progress", "noble", "econ")
WEIGHTS = {
    "points": VS.W_POINTS,
    "engine": VS.W_ENGINE_STK,
    "progress": VS.W_PROGRESS,
    "noble": VS.W_NOBLE,
    "econ": VS.W_ECON,
}


def _val(s, seat):
    return V.Valuation(s, H3.W_TEMPO, H3.W_GEM, H3.W_GOLD)


def _best_engine_card(s, seat):
    """(slot, ci, engine_value) of the board card with PTS==0 and max engine_value (>0), or None."""
    val = _val(s, seat)
    best = None
    for slot in range(12):
        ci = s.board[slot]
        if ci < 0 or E.PTS[ci] != 0:
            continue
        ev = val.engine_value(ci, seat)
        if ev > 0 and (best is None or ev > best[2]):
            best = (slot, ci, ev)
    return best


def _best_affordable_point_card(s, seat):
    """(slot, ci, take_value) of the affordable board card with PTS>0 and max take_value, or None."""
    val = _val(s, seat)
    tok, bon = s.tokens[seat], s.bonuses[seat]
    best = None
    for slot in range(12):
        ci = s.board[slot]
        if ci < 0 or E.PTS[ci] <= 0:
            continue
        if E._gold_needed(E.COST[ci], tok, bon) > tok[5]:
            continue
        tv = H3.take_value(val, ci, seat)
        if best is None or tv > best[2]:
            best = (slot, ci, tv)
    return best


def _affordable(s, seat, ci):
    return E._gold_needed(E.COST[ci], s.tokens[seat], s.bonuses[seat]) <= s.tokens[seat][5]


def _comp_me(s, seat):
    """v_state component breakdown for `seat` as the mover's own (me) values, plus value."""
    c = VS.components(s, seat)
    return {k: c[f"{k}_me"] for k in COMPS}, c["value"]


class Bucket:
    def __init__(self):
        self.n_free = 0          # every engine card found (free-acquire / bonus-only measured on all)
        self.n_real = 0          # affordable subset (real buy measured)
        self.n_point = 0
        self.dV_bonus = 0.0      # +1 bonus, KEEP board, no pay (purest test of the user's claim)
        self.dV_free = 0.0       # +1 bonus, REMOVE card (acquire minus payment; +denial confound)
        self.dV_real = 0.0       # actually buy the engine card (pays tokens, ends turn)
        self.dV_point = 0.0      # actually buy the best affordable point card (contrast)
        self.neg_bonus = 0
        self.neg_real = 0
        self.comp_bonus = {k: 0.0 for k in COMPS}   # component deltas from the bonus-only case


def probe(games: int, seed: int):
    buckets: dict[int, Bucket] = {}

    def bk(stage):
        b = (stage // 3) * 3            # stage buckets 0-2, 3-5, 6-8, ...
        return buckets.setdefault(b, Bucket())

    rng = random.Random(seed)
    for _g in range(games):
        s = E.new_game(random.Random(rng.randrange(1 << 30)))
        guard = 0
        while s.phase != E.OVER and guard < 400:
            guard += 1
            if s.phase != E.PLAY:                     # only measure clean PLAY decisions
                E.apply(s, H3.choose_action(s, s.turn))
                continue
            seat = s.turn
            eng = _best_engine_card(s, seat)
            if eng is not None:
                slot, ci, _ev = eng
                b = bk(s.purchased_n[seat])
                comp_b, V_b = _comp_me(s, seat)
                bcol = E.BONUS[ci]
                b.n_free += 1

                # BONUS-ONLY — +1 bonus, KEEP the board, no payment. The purest test of the
                # user's claim ("more engine -> progress drops"): no target lost, no denial.
                sb = s.clone()
                sb.bonuses[seat][bcol] += 1
                comp_bo, V_bo = _comp_me(sb, seat)
                b.dV_bonus += V_bo - V_b
                b.neg_bonus += 1 if V_bo < V_b else 0
                for k in COMPS:
                    b.comp_bonus[k] += WEIGHTS[k] * (comp_bo[k] - comp_b[k])

                # FREE ACQUIRE — +1 bonus AND remove the card (acquire minus payment; this
                # also denies the card to the opponent, so it reads higher than bonus-only).
                sf = s.clone()
                sf.board[slot] = -1
                sf.bonuses[seat][bcol] += 1
                _cf, V_f = _comp_me(sf, seat)
                b.dV_free += V_f - V_b

                # REAL BUY — only if affordable
                if _affordable(s, seat, ci):
                    sr = s.clone()
                    E.apply(sr, E.A_BUY_BOARD + slot)
                    _cr, V_r = _comp_me(sr, seat)
                    b.n_real += 1
                    b.dV_real += V_r - V_b
                    b.neg_real += 1 if V_r < V_b else 0

                # CONTRAST — best affordable point card
                pt = _best_affordable_point_card(s, seat)
                if pt is not None:
                    pslot, _pci, _ = pt
                    sp = s.clone()
                    E.apply(sp, E.A_BUY_BOARD + pslot)
                    _cp, V_p = _comp_me(sp, seat)
                    b.n_point += 1
                    b.dV_point += V_p - V_b

            E.apply(s, H3.choose_action(s, s.turn))

    _report(buckets)


def _avg(x, n):
    return x / n if n else float("nan")


def _report(buckets):
    print(f"\nEngine-acquisition value leak probe  (dV from the mover's perspective)\n")
    hdr = (f"{'stage':>6} {'n':>5} {'dVbonus':>8} {'<0%':>5} {'dVfree':>8} | "
           f"{'nreal':>6} {'dVreal':>8} {'<0%':>5} | {'dVpoint':>8} | "
           + " ".join(f"{'w*d'+k[:4]:>9}" for k in COMPS)
           + "    (dcomp = BONUS-ONLY, weighted contribution to standing diff)")
    print(hdr)
    print("-" * len(hdr))
    T = Bucket()
    for b in sorted(buckets):
        bu = buckets[b]
        for attr in ("n_free", "n_real", "n_point", "dV_bonus", "dV_free", "dV_real",
                     "dV_point", "neg_bonus", "neg_real"):
            setattr(T, attr, getattr(T, attr) + getattr(bu, attr))
        for k in COMPS:
            T.comp_bonus[k] += bu.comp_bonus[k]
        _row(f"{b}-{b+2}", bu)
    print("-" * len(hdr))
    _row("ALL", T)
    print("\nReading: dVbonus>0 => a +1 engine bonus (board kept) RAISES V (no leak; user's claim")
    print("refuted). dVbonus<=0 or high <0% => progress drains (claim confirmed). Compare w*dengine")
    print("(engine_stock, deck-only) vs w*dprogress: which term carries the bonus's value?")


def _row(label, bu):
    print(f"{label:>6} {bu.n_free:>5} {_avg(bu.dV_bonus, bu.n_free):>8.4f} "
          f"{100*_avg(bu.neg_bonus, bu.n_free):>4.0f}% {_avg(bu.dV_free, bu.n_free):>8.4f} | "
          f"{bu.n_real:>6} {_avg(bu.dV_real, bu.n_real):>8.4f} "
          f"{100*_avg(bu.neg_real, bu.n_real):>4.0f}% | "
          f"{_avg(bu.dV_point, bu.n_point):>8.4f} | "
          + " ".join(f"{_avg(bu.comp_bonus[k], bu.n_free):>9.4f}" for k in COMPS))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--games", type=int, default=200)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--board-w", type=float, default=None,
                    help="set v_state.ENGINE_STOCK_BOARD_W (the durable board-coverage knob) before probing")
    args = ap.parse_args()
    if args.board_w is not None:
        VS.ENGINE_STOCK_BOARD_W = args.board_w
        # WEIGHTS snapshot above already captured W_ENGINE_STK; the knob lives inside _engine_stock,
        # so component deltas for 'engine' reflect it automatically.
        print(f"[probe] ENGINE_STOCK_BOARD_W = {VS.ENGINE_STOCK_BOARD_W}")
    probe(args.games, args.seed)
