"""GENERATED by coc-core/tools/gen_board_tables.py — do not hand-edit.

Canonical space-index mapping shared with the Rust engine (coc-core). The 37-space
axial grid is identical across all 9 boards: index = spaces sorted by (r, q)."""

N_SPACES = 37

# canonical index -> space id ("q,r")
SPACE_IDS = [
    '0,-3',
    '1,-3',
    '2,-3',
    '3,-3',
    '-1,-2',
    '0,-2',
    '1,-2',
    '2,-2',
    '3,-2',
    '-2,-1',
    '-1,-1',
    '0,-1',
    '1,-1',
    '2,-1',
    '3,-1',
    '-3,0',
    '-2,0',
    '-1,0',
    '0,0',
    '1,0',
    '2,0',
    '3,0',
    '-3,1',
    '-2,1',
    '-1,1',
    '0,1',
    '1,1',
    '2,1',
    '-3,2',
    '-2,2',
    '-1,2',
    '0,2',
    '1,2',
    '-3,3',
    '-2,3',
    '-1,3',
    '0,3',
]

# space id -> canonical index
INDEX_OF = {sid: i for i, sid in enumerate(SPACE_IDS)}


def board_index(board_id) -> int:
    """Board id "1".."9" -> 0..8 (unknown/None falls back to the default board 0),
    mirroring board.get_board's fallback."""
    try:
        i = int(board_id) - 1
    except (TypeError, ValueError):
        return 0
    return i if 0 <= i < 9 else 0
