"""Generate coc-core/src/boards_gen.rs + games/castles_of_crimson/az/spaces.py.

Reads the authoritative board data (games/castles_of_crimson/board.py) and emits static
int tables for the Rust engine, plus the canonical space-index mapping for the Python
bridge. NEVER hand-edit the generated files — rerun this script.

Canonical space index (the load-bearing convention shared by Rust, the projection, the
action space's A_SPACE head, and the feature encoder): the 37 spaces sorted by (r, q).
The (q, r) grid — and therefore adjacency — is identical across all 9 boards (asserted
here), so SPACE_QR / NEIGHBOR_MASK are emitted once, board-independent; color/number/
region tables are per-board.

Region index (per board): for each color in board.COLORS order, that color's regions
sorted by their minimum canonical space index. Deterministic and reconstructable.

Run:  python coc-core/tools/gen_board_tables.py
"""
from __future__ import annotations

import os
import sys

_REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, _REPO)

from games.castles_of_crimson import board  # noqa: E402

RS_OUT = os.path.join(_REPO, "coc-core", "src", "boards_gen.rs")
PY_OUT = os.path.join(_REPO, "games", "castles_of_crimson", "az", "spaces.py")

COLORS = board.COLORS  # burgundy, blue, gray, green, beige, yellow
BOARD_IDS = [str(i) for i in range(1, 10)]


def canonical_spaces(b: board.Board) -> list[str]:
    return sorted(b.SPACES, key=lambda sid: (b.SPACES[sid]["r"], b.SPACES[sid]["q"]))


def main() -> None:
    boards = [board.BOARDS[bid] for bid in BOARD_IDS]

    # ── canonical grid (board-independent; assert) ──
    grid = canonical_spaces(boards[0])
    assert len(grid) == 37
    for b in boards[1:]:
        assert canonical_spaces(b) == grid, f"board {b.id} grid differs"
    index_of = {sid: i for i, sid in enumerate(grid)}

    space_qr = [board.parse_space_id(sid) for sid in grid]

    # adjacency masks (board-independent; assert identical across boards)
    nbr_mask = []
    for i, sid in enumerate(grid):
        m = 0
        for nb in boards[0].ADJACENCY[sid]:
            m |= 1 << index_of[nb]
        nbr_mask.append(m)
    for b in boards[1:]:
        for i, sid in enumerate(grid):
            m = 0
            for nb in b.ADJACENCY[sid]:
                m |= 1 << index_of[nb]
            assert m == nbr_mask[i], f"board {b.id} adjacency differs at {sid}"

    # ── per-board tables ──
    space_color = []   # [board][37] color idx
    space_number = []  # [board][37] 1..6
    color_mask = []    # [board][6] u64
    region_of = []     # [board][37] region idx
    regions = []       # [board] -> list of (color_idx, size, mask, has_castle)
    region_indices = []  # [board] -> {region id str: canonical region idx}
    for b in boards:
        sc, sn = [], []
        for sid in grid:
            info = b.SPACES[sid]
            sc.append(COLORS.index(info["color"]))
            sn.append(info["number"])
        space_color.append(sc)
        space_number.append(sn)

        cm = []
        for c in COLORS:
            m = 0
            for sid in b.SPACES_BY_COLOR[c]:
                m |= 1 << index_of[sid]
            cm.append(m)
        color_mask.append(cm)

        # deterministic region order: color order, then min canonical index
        regs = []
        reg_index = {}  # region id string -> canonical region index (for spaces.py)
        for ci, c in enumerate(COLORS):
            col_regs = [r for r in b.REGIONS.values() if r["color"] == c]
            col_regs.sort(key=lambda r: min(index_of[s] for s in r["spaces"]))
            for r in col_regs:
                m = 0
                for s in r["spaces"]:
                    m |= 1 << index_of[s]
                reg_index[r["id"]] = len(regs)
                regs.append((ci, r["size"], m, r["has_castle"]))
        # sanity: regions partition the 37 spaces
        assert sum(r[1] for r in regs) == 37
        ro = [0] * 37
        for ri, (_ci, _sz, m, _hc) in enumerate(regs):
            for i in range(37):
                if m >> i & 1:
                    ro[i] = ri
        regions.append(regs)
        region_of.append(ro)
        region_indices.append(reg_index)

    n_regions = [len(r) for r in regions]
    max_regions = max(n_regions)

    # ── emit Rust ──
    def rows(fmt, per_board):
        return ",\n".join("    [" + ", ".join(fmt(v) for v in row) + "]" for row in per_board)

    pad = lambda lst, fill: lst + [fill] * (max_regions - len(lst))
    reg_color = [pad([r[0] for r in regs], 0) for regs in regions]
    reg_size = [pad([r[1] for r in regs], 0) for regs in regions]
    reg_mask = [pad([r[2] for r in regs], 0) for regs in regions]
    reg_castle = [pad([r[3] for r in regs], False) for regs in regions]

    rs = []
    rs.append("//! GENERATED by coc-core/tools/gen_board_tables.py — do not hand-edit.")
    rs.append("//! Source of truth: games/castles_of_crimson/board.py (the 9 duchy boards).")
    rs.append("//! Canonical space index = spaces sorted by (r, q); identical grid on all boards.")
    rs.append("")
    rs.append("pub const N_BOARDS: usize = 9;")
    rs.append("pub const N_SPACES: usize = 37;")
    rs.append(f"pub const MAX_REGIONS: usize = {max_regions};")
    rs.append("")
    rs.append("/// Colors: 0=burgundy(castle) 1=blue(ship) 2=gray(mine) 3=green(livestock)")
    rs.append("/// 4=beige(building) 5=yellow(monastery) — board.py COLORS order.")
    rs.append("pub const N_COLORS: usize = 6;")
    rs.append("")
    rs.append("/// Axial (q, r) per canonical space index (board-independent).")
    rs.append("pub static SPACE_QR: [(i8, i8); N_SPACES] = [")
    rs.append("    " + ", ".join(f"({q}, {r})" for q, r in space_qr))
    rs.append("];")
    rs.append("")
    rs.append("/// 37-bit adjacency mask per space (board-independent — same grid everywhere).")
    rs.append("pub static NEIGHBOR_MASK: [u64; N_SPACES] = [")
    rs.append("    " + ", ".join(f"0x{m:010x}" for m in nbr_mask))
    rs.append("];")
    rs.append("")
    rs.append("pub static SPACE_COLOR: [[u8; N_SPACES]; N_BOARDS] = [")
    rs.append(rows(str, space_color))
    rs.append("];")
    rs.append("")
    rs.append("pub static SPACE_NUMBER: [[u8; N_SPACES]; N_BOARDS] = [")
    rs.append(rows(str, space_number))
    rs.append("];")
    rs.append("")
    rs.append("/// All spaces of a color, per board (color-completion / bonus-tile checks).")
    rs.append("pub static COLOR_MASK: [[u64; N_COLORS]; N_BOARDS] = [")
    rs.append(rows(lambda m: f"0x{m:010x}", color_mask))
    rs.append("];")
    rs.append("")
    rs.append("pub static N_REGIONS: [u8; N_BOARDS] = [" + ", ".join(map(str, n_regions)) + "];")
    rs.append("")
    rs.append("/// Region index per space, per board (region order: color, then min space index).")
    rs.append("pub static REGION_OF: [[u8; N_SPACES]; N_BOARDS] = [")
    rs.append(rows(str, region_of))
    rs.append("];")
    rs.append("")
    rs.append("pub static REGION_COLOR: [[u8; MAX_REGIONS]; N_BOARDS] = [")
    rs.append(rows(str, reg_color))
    rs.append("];")
    rs.append("")
    rs.append("pub static REGION_SIZE: [[u8; MAX_REGIONS]; N_BOARDS] = [")
    rs.append(rows(str, reg_size))
    rs.append("];")
    rs.append("")
    rs.append("pub static REGION_MASK: [[u64; MAX_REGIONS]; N_BOARDS] = [")
    rs.append(rows(lambda m: f"0x{m:010x}", reg_mask))
    rs.append("];")
    rs.append("")
    rs.append("/// Whether the region contains a burgundy (castle) space.")
    rs.append("pub static REGION_HAS_CASTLE: [[bool; MAX_REGIONS]; N_BOARDS] = [")
    rs.append(rows(lambda v: "true" if v else "false", reg_castle))
    rs.append("];")
    rs.append("")
    with open(RS_OUT, "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(rs))

    # ── emit Python mirror ──
    py = []
    py.append('"""GENERATED by coc-core/tools/gen_board_tables.py — do not hand-edit.')
    py.append("")
    py.append("Canonical space-index mapping shared with the Rust engine (coc-core). The 37-space")
    py.append('axial grid is identical across all 9 boards: index = spaces sorted by (r, q)."""')
    py.append("")
    py.append("N_SPACES = 37")
    py.append("")
    py.append("# canonical index -> space id (\"q,r\")")
    py.append("SPACE_IDS = [")
    for sid in grid:
        py.append(f"    {sid!r},")
    py.append("]")
    py.append("")
    py.append("# space id -> canonical index")
    py.append("INDEX_OF = {sid: i for i, sid in enumerate(SPACE_IDS)}")
    py.append("")
    py.append(f"MAX_REGIONS = {max_regions}")
    py.append("")
    py.append("# per board (index 0..8): region id string -> canonical region index")
    py.append("# (region order: color order, then min canonical space index — matches boards_gen.rs)")
    py.append("REGION_INDEX = [")
    for reg_index in region_indices:
        items = ", ".join(f"{rid!r}: {i}" for rid, i in reg_index.items())
        py.append("    {" + items + "},")
    py.append("]")
    py.append("")
    py.append("")
    py.append("def board_index(board_id) -> int:")
    py.append('    """Board id \"1\"..\"9\" -> 0..8 (unknown/None falls back to the default board 0),')
    py.append('    mirroring board.get_board\'s fallback."""')
    py.append("    try:")
    py.append("        i = int(board_id) - 1")
    py.append("    except (TypeError, ValueError):")
    py.append("        return 0")
    py.append("    return i if 0 <= i < 9 else 0")
    py.append("")
    with open(PY_OUT, "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(py))

    print(f"wrote {RS_OUT}")
    print(f"wrote {PY_OUT}  (N_SPACES=37, MAX_REGIONS={max_regions}, n_regions={n_regions})")


if __name__ == "__main__":
    main()
